### ISSUE TITLE
Our Kafka  Reactive Consumer Run into Exponential BackOFF In production and solves only on restarting the pods

### ISSUE THREAD

**Issue by MOHAMEDSAMEEM77** [reactor/reactor-kafka#291]
Sharing the Reactive  Functions and their ErrorHandling Systems Taken
```yaml
application.yml :
        verifyxyz-in-0:
          destination: xyz_verify
          group: data-here
          contentType: application/json
          consumer:
            autoCommitOffset: true
            autoCommitOnError: true
            maxAttempts: 1
         xyz-data-verify:
          destination: xyz_verify
          binder: kafka
          contentType: application/json


        verifyf2-in-0:
          destination: f2_verify
          binder: kafka
          group: data-here
          contentType: application/json
          consumer:
            autoCommitOffset: true
            autoCommitOnError: true
            maxAttempts: 1
         verifyf2-out-0:
          destination: another_kafka_topic
          binder: kafka
          group: docService
          contentType: application/json
```

```java
//first consumer type
@Bean
Consumer<Flux<String>> verifyxyz() {
        return flux.flatMap(v ->{
                                 // reactive downstream codes
                  })
                  .onErrorReturn("Failed String Message Error");
}

//second consumer type
Function<Flux<String>, Flux<Message<String>>> verifyf2(){
 return flux.flatMap(v ->{
             })
            .onErrorReturn((MessageBuilder.withPayload("Failed Message").build()));
}
```
